vich_uploader:
    db_driver: orm
    mappings:
        school_logos:
            uri_prefix:         "%school_logos%"
            upload_destination: "%kernel.project_dir%/public/%school_logos%"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        school_images:
            uri_prefix:         "%school_images%"
            upload_destination: "%kernel.project_dir%/public/%school_images%"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer