homepage:
    path: /
    defaults:  { _controller: App\Controller\DefaultController::indexAction }

easy_admin_bundle:
    resource: '@EasyAdminBundle/Controller/EasyAdminController.php'
    prefix: /admin
    type: annotation

api_auth_login:
    path: /api/auth/login
    methods:  [POST]

api:
    prefix: /api
    resource: '../src/Controller/Api'


fos_user_security_login:
    path: /login
    defaults:  { _controller: App\Controller\SecurityController::loginAction}
