# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    school_logos: "/uploads/logos"
    school_images: "/uploads/images"
    region:
        Far West: Far West
        South East: South East
        Rocky Mountains: Rocky Mountains
        Great Lakes: Great Lakes
        South West: South West
        Mid East: Mid East
        Plains: Plains
        New England: New England
    schoolTerms:
        2020-21: 2020-21
        2021-22: 2021-22
        2022-23: 2022-23
        2023-24: 2023-24
        2024-25: 2024-25
        2025-26: 2025-26
        2026-27: 2026-27
        2027-28: 2027-28
        2028-29: 2028-29
        2029-30: 2029-30
        2030-31: 2030-31
    raceEthnicity:
        Asian: asian
        American Indian or Alaskan Native: AIAN
        Black or African American: BAA
        Hispanic/Latino: H/L
        Native Hawaiian or other Pacific Islander: NHOPI
        White: white
        Two or more races: TmR
        Race/ethnicity unknown: R/Eu
        Non-resident alien: N-RA
    firstGeneration:
        Yes: 1
        No: 0
    activeMilitary:
        Yes: 1
        No: 0
    collegeCategory:
        Schools under $20,000: SchoolsUnder$20,000
        Schools with 100% Acceptence Rate: SchoolsWith100%AcceptenceRate
        Public Schools: PublicSchools
        Private Schools: PrivateSchools
        Historically Black Colleges and Universities: HistoricallyBlackCollegesAndUniversities
        2-Year Programs: 2-YearPrograms
        4-Year Programs: 4-YearPrograms
        Ivy League: IvyLeague
        Highest Graduation rate: HighestGraduationRate
    states:
        Alabama: Alabama
        Alaska: Alaska
        America: Samoa
        Arizona: Arizona
        Arkansas: Arkansas
        California: California
        Colorado: Colorado
        Connecticut: Connecticut
        Delaware: Delaware
        District of Columbia: District Of Columbia
        Florida: Florida
        Georgia: Georgia
        Guam: Guam
        Hawaii: Hawaii
        Idaho: Idaho
        Illinois: Illinois
        Indiana: Indiana
        Iowa: Iowa
        Kansas: Kansas
        Kentucky: Kentucky
        Louisiana: Louisiana
        Maine: Maine
        Maryland: Maryland
        Massachusetts: Massachusetts
        Michigan: Michigan
        Minnesota: Minnesota
        Mississippi: Mississippi
        Missouri: Missouri
        Montana: Montana
        Nebraska: Nebraska
        Nevada: Nevada
        New Hampshire: New Hampshire
        New Jersey: New Jersey
        New Mexico: New Mexico
        New York: New York
        North Carolina: North Carolina
        North Dakota: Noth Dakota
        Nothern Mariana Islands: Nothern Mariana Islands
        Ohio: Ohio
        Oklahoma: Oklahoma
        Oregon: Oregon
        Pennsylvania: Pennsylvania
        Puerto Rico: Puerto Rico
        Rhode Island: Rhode Island
        South Carolina: South Carolina
        South Dakota: South Dakota
        Tennessee: Tennessee
        Texas: Texas
        Utah: Utah
        Vermont: Vermont
        Virgin Islands: Virgin Islands
        Virginia: Virginia
        Washington: Washington
        West Virginia: West Virginia
        Wisconsin: Wisconsin
        Wyoming: Wyoming
    campusSetting:
        Choose Campus Setting: ''
        'City: Small': citySmall
        'City: Midsize': cityMidsize
        'City: Large': cityLarge
        'Suburb: Small': suburbSmall
        'Suburb: Midsize': suburbMidsize
        'Suburb: Large': suburbLarge
        'Town: Remote': townRemote
        'Town: Fringe': townFringe
        'Town: Distant': townDistant
        'Rural: Remote': ruralRemote
        'Rural: Fringe': ruralFringe
        'Rural: Distant': ruralDistant

    clubActivities:
        Nothing Selected: ''
        Academic Clubs: Academic Clubs
        Political Clubs: Political Clubs
        Media & Publication Groups: Media & Publication Groups
        Community Service & Social Justice: Community Service & Social Justice
        Theater & The Arts: Theater & The Arts
        Cultural Clubs: Cultural Clubs
        Religious & Spiritual Groups:  Religious & Spiritual Groups
        Sports & Recreation: Sports & Recreation

    sports:
        Frisbee: Frisbee
        Indoor: Indoor
        Rowing: Rowing
        Softball: Softball
        Field Hockey: FieldHockey
        Baseball: Baseball
        Basketball: Basketball
        Bicycling: Bicycling
        Billiards: Billiards
        Bodybuilding: Bodybuilding
        Bowling: Bowling
        Boxing: Boxing
        Car Racing: CarRacing
        Cheerleading: Cheerleading
        Cricket: Cricket
        Extreme Sports: ExtremeSports
        Football: Football
        Golf: Golf
        Gymnastics: Gymnastics
        Ice Hockey: IceHockey
        Lacrosse: Lacrosse
        Martial Arts: MartialArts
        None: None
        Other Activities: OtherActivities
        Skateboarding: Skateboarding
        Skating: Skating
        Paintball: Paintball
        Soccer: Soccer
        Swimming and Diving: SwimmingAndDiving
        Table Tennis: TableTennis
        Tennis: Tennis
        Track and Field: TrackAndField
        Volleyball: Volleyball
        Wrestling: Wrestling
    sportsPlaceholder:
        Frisbee: Frisbee
        Indoor: Indoor
        Rowing: Rowing
        Softball: Softball
        Field Hockey: Field Hockey
        Baseball: Baseball
        Basketball: Basketball
        Bicycling: Bicycling
        Billiards: Billiards
        Bodybuilding: Bodybuilding
        Bowling: Bowling
        Boxing: Boxing
        Car Racing: Car Racing
        Cheerleading: Cheerleading
        Cricket: Cricket
        Extreme Sports: Extreme Sports
        Football: Football
        Golf: Golf
        Gymnastics: Gymnastics
        Ice Hockey: Ice Hockey
        Lacrosse: Lacrosse
        Martial Arts: Martial Arts
        None: None
        Other Activities: Other Activities
        Skateboarding: Skateboarding
        Skating: Skating
        Paintball: Paintball
        Soccer: Soccer
        Swimming and Diving: Swimming and Diving
        Table Tennis: Table Tennis
        Tennis: Tennis
        Track and Field: Track and Field
        Volleyball: Volleyball
        Wrestling: Wrestling

    programsMajor:
        Agriculture & Related Sciences: Agriculture & Related Sciences
        Area, Ethnic, Cultural, Gender & Group Studies: Area, Ethnic, Cultural, Gender & Group Studies
        Biological & Biomedical Sciences: Biological & Biomedical Sciences
        Business, Management, Marketing & Related Services: Business, Management, Marketing & Related Services
        Communication Technologies/Technicians & Support Services: Communication Technologies/Technicians & Support Services
        Communication, Journalism & Related Programs: Communication, Journalism & Related Programs
        Computer and Information Sciences: Computer and Information Sciences
        Construction Trades: Construction Trades
        Education: Education
        Engineering: Engineering
        Engineering Technology & Related Field: Engineering Technology & Related Field
        English Language & Literature: English Language & Literature
        Family & Consumer Sciences: Family & Consumer Sciences
        Foreign Languages, Literatures & Linguistics: Foreign Languages, Literatures & Linguistics
        Health Profession & Related Programs: Health Profession & Related Programs
        History: History
        Homeland Security, Law Enforcement, & Related Services: Homeland Security, Law Enforcement, & Related Services
        Legal Professions & Studies: Legal Professions & Studies
        Liberal Arts & Sciences: Liberal Arts & Sciences
        Library Science: Library Science
        Mathematics & Statistics: Mathematics & Statistics
        Mechanic & Repair Technologies: Mechanic & Repair Technologies
        Military Technologies & Applied Sciences: Military Technologies & Applied Sciences
        Multi/Interdisciplinary Studies: Multi/Interdisciplinary Studies
        Natural Resources & Conservation: Natural Resources & Conservation
        Parks, Recreation, Leisure & Fitness Studies: Parks, Recreation, Leisure & Fitness Studies
        Personal & Culinary Services: Personal & Culinary Services
        Philosophy & Religious Studies: Philosophy & Religious Studies
        Physical Sciences: Physical Sciences
        Precision Production: Precision Production
        Psychology: Psychology
        Public Administration & Social Services: Public Administration & Social Services
        Science Technologies: Science Technologies
        Social Sciences: Social Sciences
        Theology & Religious Vocations: Theology & Religious Vocations
        Transportation & Materials Moving: Transportation & Materials Moving
        Visual & Performing Arts: Visual & Performing Arts


services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
